#if !defined(custom_uuid_h)
#define custom_uuid_h

#ifdef __cplusplus
    extern "C" {
#endif

/* The Company identified */

#define BT_COMPANY_ID_CODE      0x0059

/* UUID generated by https://uuidonline.net */

/* Serivce UUID*/

#define BT_UUID_SERVICE_VAL     BT_UUID_128_ENCODE(0x14d34c80, 0x3215, 0x56f5, 0x8116, 0xd41bcce1b00b)

/* Characteristic UUID */

#define BT_UUID_CONFIG_VAL      BT_UUID_128_ENCODE(0xaa3dc387, 0x21fb, 0x5462, 0xabc2, 0xaa7c88669b18)
#define BT_UUID_STATUS_VAL      BT_UUID_128_ENCODE(0x8eff2f37, 0x20fa, 0x506d, 0xb8ab, 0xb173d91675a6)


#define BT_UUID_SERVICE         BT_UUID_DECLARE_128(BT_UUID_SERVICE_VAL)
#define BT_UUID_CONFIG          BT_UUID_DECLARE_128(BT_UUID_CONFIG_VAL)
#define BT_UUID_STATUS          BT_UUID_DECLARE_128(BT_UUID_STATUS_VAL)

#ifdef __cplusplus
    }
#endif

#endif